project 'GPUImage.xcodeproj'
platform :ios, '9.0'

target 'GPUImage' do
  use_frameworks!
  pod 'MoltenGL', '~> 0.23.0'
end

target 'GPUImageFramework' do
  use_frameworks!
  pod 'MoltenGL', '~> 0.23.0'
end
